=== KinaMarie/skdb/doc/DTD/site.dtd
<?xml version="1.0"?>
<!ELEMENT site (name, locname, longitude, latitude, website, access, equipment, datetime)>
	<!ATTLIST site id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT locname (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT access (#PCDATA)>
<!ELEMENT equipment (equipment-item*)>
<!ELEMENT equipment-item (type, maker, notes, capabilities)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT maker (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ELEMENT capabilities (capability*)>
<!ELEMENT capability (#PCDATA)>
	<!ATTLIST capability id CDATA #REQUIRED>

<!ELEMENT datetime (#PCDATA)>

=== KinaMarie/skdb/unittests/sitetest.xml
<?xml version="1.0"?>
<!DOCTYPE site PUBLIC "-//TangibleBit//DTD siteDef 1.0//EN" "http://tangiblebit.com/dtd/site.dtd">
<site id="1">
	<name>Testsite</name>
	<locname>Antarctica</locname>
	<longitude>0</longitude>
	<latitude>-90.0</latitude>
	<website>http://antarcticfablab.int</website>
	<access>Fab Lab</access>
	<equipment>
		<equipment-item>
			<type>Epilog Mini 24</type>
			<maker>Epilog</maker>
			<capabilities>
				<capability>Laser Cutter</capability>
			</capabilities>
		</equipment-item>
		<equipment-item>
			<type>Shopbot PRSAlpha 96</type>
			<maker>Shopbot tools</maker>
			<capabilities>
				<capability>CNC Mill</capability>
			</capabilities>
		</equipment-item>
	</equipment>
</site>
